name: ci-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      # Pega os arquivos do que acabou de subir e baixa nesse ubuntu
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go test
      - run: go run math.go